version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ort-receiver"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-88ekrhe09ssj"
s3_prefix = "ort-receiver"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
